// Intent citation: .kiro/specs/mesh-network-optimizer/design.md Section 3.7
// Incentive Enforcement — free-rider detection, escalation ladder, recovery

use crate::mesh::identity::MeshId;
use crate::transport::trait_def::NodeId;
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};

// ─── Free-Rider Status ───────────────────────────────────────────────────────

/// Current enforcement status for a node.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum FreeRiderStatus {
    /// Node is in good standing.
    Good,
    /// Warning issued (cycle 3 of negative balance).
    Warning { since_cycle: u32 },
    /// Deprioritized routing (cycles 4-5).
    Deprioritized { since_cycle: u32 },
    /// Excluded from shared model allocations (cycle 6+).
    Excluded { since_cycle: u32 },
}

/// Notification generated by the incentive enforcer.
#[derive(Debug, Clone, PartialEq)]
pub enum IncentiveNotification {
    Warning { node_id: NodeId, message: String },
    Deprioritized { node_id: NodeId },
    Excluded { node_id: NodeId },
    Recovered { node_id: NodeId },
}

// ─── Node Incentive State ────────────────────────────────────────────────────

/// Tracked incentive state for a single node.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NodeIncentiveState {
    pub node_id: NodeId,
    pub mesh_id: MeshId,
    pub status: FreeRiderStatus,
    pub consecutive_negative_cycles: u32,
    pub consecutive_positive_cycles: u32,
    pub is_consumer_only_exempt: bool,
}

// ─── Incentive Enforcer ──────────────────────────────────────────────────────

/// Enforces fair contribution via free-rider detection and escalation.
pub struct IncentiveEnforcer {
    /// Per-node incentive state: (mesh_id, node_id) -> state.
    states: HashMap<(MeshId, NodeId), NodeIncentiveState>,
    /// Consumer-only exempt nodes.
    exempt_nodes: HashSet<(MeshId, NodeId)>,
    /// Configuration: grace cycles before warning (default: 2).
    pub grace_cycles: u32,
    /// Cycle at which warning is issued (default: 3).
    pub warning_cycle: u32,
    /// Cycles at which deprioritization starts (default: 4).
    pub deprioritize_cycle: u32,
    /// Cycle at which exclusion starts (default: 6).
    pub exclude_cycle: u32,
    /// Consecutive positive cycles needed for recovery (default: 2).
    pub recovery_cycles: u32,
}

impl IncentiveEnforcer {
    pub fn new() -> Self {
        Self {
            states: HashMap::new(),
            exempt_nodes: HashSet::new(),
            grace_cycles: 2,
            warning_cycle: 3,
            deprioritize_cycle: 4,
            exclude_cycle: 6,
            recovery_cycles: 2,
        }
    }

    /// Register a node for incentive tracking.
    pub fn register_node(&mut self, node_id: NodeId, mesh_id: MeshId) {
        let key = (mesh_id, node_id);
        if !self.states.contains_key(&key) {
            self.states.insert(
                key,
                NodeIncentiveState {
                    node_id,
                    mesh_id,
                    status: FreeRiderStatus::Good,
                    consecutive_negative_cycles: 0,
                    consecutive_positive_cycles: 0,
                    is_consumer_only_exempt: false,
                },
            );
        }
    }

    /// Designate a node as consumer-only (exempt from free-rider detection).
    pub fn set_consumer_only_exempt(&mut self, node_id: NodeId, mesh_id: MeshId, exempt: bool) {
        let key = (mesh_id, node_id);
        if exempt {
            self.exempt_nodes.insert(key);
        } else {
            self.exempt_nodes.remove(&key);
        }
        if let Some(state) = self.states.get_mut(&key) {
            state.is_consumer_only_exempt = exempt;
        }
    }

    /// Check if a node is consumer-only exempt.
    pub fn is_exempt(&self, node_id: &NodeId, mesh_id: &MeshId) -> bool {
        self.exempt_nodes.contains(&(*mesh_id, *node_id))
    }

    /// Get the current free-rider status for a node.
    pub fn get_status(&self, node_id: &NodeId, mesh_id: &MeshId) -> Option<&FreeRiderStatus> {
        self.states.get(&(*mesh_id, *node_id)).map(|s| &s.status)
    }

    /// Process a cycle update for a node. Called once per optimization cycle.
    /// Returns any notification generated by the escalation/recovery logic.
    pub fn process_cycle(
        &mut self,
        node_id: &NodeId,
        mesh_id: &MeshId,
        balance: f64,
        current_cycle: u32,
    ) -> Option<IncentiveNotification> {
        let key = (*mesh_id, *node_id);

        // Exempt nodes are never flagged
        if self.exempt_nodes.contains(&key) {
            return None;
        }

        let state = self.states.get_mut(&key)?;

        if balance < 0.0 {
            // Negative balance cycle
            state.consecutive_negative_cycles += 1;
            state.consecutive_positive_cycles = 0;

            // Escalation ladder
            let neg = state.consecutive_negative_cycles;

            if neg <= self.grace_cycles {
                // Cycles 1-2: grace period, no action
                state.status = FreeRiderStatus::Good;
                None
            } else if neg == self.warning_cycle {
                // Cycle 3: warning
                state.status = FreeRiderStatus::Warning {
                    since_cycle: current_cycle,
                };
                Some(IncentiveNotification::Warning {
                    node_id: *node_id,
                    message: "Your contribution balance is negative for 3 cycles. Consider contributing more resources.".to_string(),
                })
            } else if neg >= self.deprioritize_cycle && neg < self.exclude_cycle {
                // Cycles 4-5: deprioritized
                state.status = FreeRiderStatus::Deprioritized {
                    since_cycle: current_cycle,
                };
                Some(IncentiveNotification::Deprioritized { node_id: *node_id })
            } else if neg >= self.exclude_cycle {
                // Cycle 6+: excluded
                state.status = FreeRiderStatus::Excluded {
                    since_cycle: current_cycle,
                };
                Some(IncentiveNotification::Excluded { node_id: *node_id })
            } else {
                None
            }
        } else {
            // Positive or zero balance
            if state.consecutive_negative_cycles > 0 {
                state.consecutive_positive_cycles += 1;

                if state.consecutive_positive_cycles >= self.recovery_cycles {
                    // Recovery: 2 consecutive positive cycles restores full participation
                    state.status = FreeRiderStatus::Good;
                    state.consecutive_negative_cycles = 0;
                    state.consecutive_positive_cycles = 0;
                    Some(IncentiveNotification::Recovered { node_id: *node_id })
                } else {
                    None
                }
            } else {
                // Already good, nothing to do
                state.consecutive_positive_cycles = 0;
                None
            }
        }
    }

    /// Check if a node should be excluded from shared model allocations.
    pub fn is_excluded(&self, node_id: &NodeId, mesh_id: &MeshId) -> bool {
        matches!(
            self.get_status(node_id, mesh_id),
            Some(FreeRiderStatus::Excluded { .. })
        )
    }

    /// Check if a node is deprioritized (should go to back of queue).
    pub fn is_deprioritized(&self, node_id: &NodeId, mesh_id: &MeshId) -> bool {
        matches!(
            self.get_status(node_id, mesh_id),
            Some(FreeRiderStatus::Deprioritized { .. })
        )
    }

    /// Remove a node from tracking (for retirement/leave).
    pub fn remove_node(&mut self, node_id: &NodeId, mesh_id: &MeshId) {
        let key = (*mesh_id, *node_id);
        self.states.remove(&key);
        self.exempt_nodes.remove(&key);
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;
    use uuid::Uuid;

    proptest! {
        /// Property: escalation follows exact ladder timing.
        #[test]
        fn prop_escalation_ladder_timing(
            num_negative_cycles in 1u32..15
        ) {
            let mut enforcer = IncentiveEnforcer::new();
            let mesh_id = Uuid::new_v4();
            let node_id = Uuid::new_v4();
            enforcer.register_node(node_id, mesh_id);

            for cycle in 1..=num_negative_cycles {
                enforcer.process_cycle(&node_id, &mesh_id, -1.0, cycle);
            }

            let status = enforcer.get_status(&node_id, &mesh_id).unwrap();

            if num_negative_cycles <= 2 {
                prop_assert_eq!(status.clone(), FreeRiderStatus::Good);
            } else if num_negative_cycles == 3 {
                let is_warning = matches!(status, FreeRiderStatus::Warning { .. });
                prop_assert!(is_warning);
            } else if num_negative_cycles <= 5 {
                let is_deprioritized = matches!(status, FreeRiderStatus::Deprioritized { .. });
                prop_assert!(is_deprioritized);
            } else {
                let is_excluded = matches!(status, FreeRiderStatus::Excluded { .. });
                prop_assert!(is_excluded);
            }
        }

        /// Property: recovery requires exactly 2 positive cycles.
        #[test]
        fn prop_recovery_requires_two_positive(
            negative_cycles in 3u32..10,
            positive_cycles in 1u32..5
        ) {
            let mut enforcer = IncentiveEnforcer::new();
            let mesh_id = Uuid::new_v4();
            let node_id = Uuid::new_v4();
            enforcer.register_node(node_id, mesh_id);

            // Drive into negative territory
            for cycle in 1..=negative_cycles {
                enforcer.process_cycle(&node_id, &mesh_id, -1.0, cycle);
            }

            // Now apply positive cycles
            for cycle in 0..positive_cycles {
                enforcer.process_cycle(&node_id, &mesh_id, 1.0, negative_cycles + cycle + 1);
            }

            let status = enforcer.get_status(&node_id, &mesh_id).unwrap();

            if positive_cycles >= 2 {
                prop_assert_eq!(status.clone(), FreeRiderStatus::Good, "Should recover after 2 positive cycles");
            } else {
                prop_assert_ne!(status.clone(), FreeRiderStatus::Good, "Should NOT recover after only {} positive cycle(s)", positive_cycles);
            }
        }

        /// Property: exempt nodes are never flagged.
        #[test]
        fn prop_exempt_nodes_never_flagged(
            num_cycles in 1u32..20
        ) {
            let mut enforcer = IncentiveEnforcer::new();
            let mesh_id = Uuid::new_v4();
            let node_id = Uuid::new_v4();
            enforcer.register_node(node_id, mesh_id);
            enforcer.set_consumer_only_exempt(node_id, mesh_id, true);

            for cycle in 1..=num_cycles {
                let notification = enforcer.process_cycle(&node_id, &mesh_id, -10.0, cycle);
                prop_assert_eq!(notification, None, "Exempt node should never get notifications");
            }

            let status = enforcer.get_status(&node_id, &mesh_id).unwrap();
            prop_assert_eq!(status.clone(), FreeRiderStatus::Good, "Exempt node should always be Good");
        }

        /// Property: excluded nodes don't receive shared model allocations.
        #[test]
        fn prop_excluded_nodes_no_allocations(
            _dummy in 0u8..10
        ) {
            let mut enforcer = IncentiveEnforcer::new();
            let mesh_id = Uuid::new_v4();
            let node_id = Uuid::new_v4();
            enforcer.register_node(node_id, mesh_id);

            // Drive to exclusion (6 negative cycles)
            for cycle in 1..=6 {
                enforcer.process_cycle(&node_id, &mesh_id, -1.0, cycle);
            }

            prop_assert!(enforcer.is_excluded(&node_id, &mesh_id));
        }
    }

    // ─── Unit Tests ──────────────────────────────────────────────────────────

    #[test]
    fn test_full_escalation_and_recovery_cycle() {
        let mut enforcer = IncentiveEnforcer::new();
        let mesh_id = Uuid::new_v4();
        let node_id = Uuid::new_v4();
        enforcer.register_node(node_id, mesh_id);

        // Cycles 1-2: grace
        assert_eq!(enforcer.process_cycle(&node_id, &mesh_id, -1.0, 1), None);
        assert_eq!(enforcer.process_cycle(&node_id, &mesh_id, -1.0, 2), None);

        // Cycle 3: warning
        let n = enforcer.process_cycle(&node_id, &mesh_id, -1.0, 3);
        assert!(matches!(n, Some(IncentiveNotification::Warning { .. })));

        // Cycle 4: deprioritized
        let n = enforcer.process_cycle(&node_id, &mesh_id, -1.0, 4);
        assert!(matches!(n, Some(IncentiveNotification::Deprioritized { .. })));

        // Cycle 5: still deprioritized
        let n = enforcer.process_cycle(&node_id, &mesh_id, -1.0, 5);
        assert!(matches!(n, Some(IncentiveNotification::Deprioritized { .. })));

        // Cycle 6: excluded
        let n = enforcer.process_cycle(&node_id, &mesh_id, -1.0, 6);
        assert!(matches!(n, Some(IncentiveNotification::Excluded { .. })));

        // Recovery: 1 positive cycle — not enough
        assert_eq!(enforcer.process_cycle(&node_id, &mesh_id, 1.0, 7), None);
        assert!(enforcer.is_excluded(&node_id, &mesh_id));

        // Recovery: 2nd positive cycle — recovered
        let n = enforcer.process_cycle(&node_id, &mesh_id, 1.0, 8);
        assert_eq!(n, Some(IncentiveNotification::Recovered { node_id }));
        assert!(!enforcer.is_excluded(&node_id, &mesh_id));
    }
}
