// Intent citation: .kiro/specs/mesh-network-optimizer/design.md Section 5
// Cross-Network Model Transfer — peer discovery, single/parallel transfer, verification

use crate::mesh::accounting::AccountingType;
use crate::mesh::identity::MeshId;
use crate::mesh::solver::ModelId;
use crate::transport::trait_def::NodeId;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use uuid::Uuid;

// ─── Transfer Types ──────────────────────────────────────────────────────────

/// Status of a model transfer.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum TransferStatus {
    Pending,
    InProgress { progress_percent: f64 },
    Completed { checksum_verified: bool },
    Failed { reason: String },
}

/// A chunk assignment for parallel transfer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChunkAssignment {
    pub source_node: NodeId,
    pub offset: u64,
    pub size: u64,
    pub received: bool,
    pub checksum: Option<u32>,
}

/// A model transfer operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelTransfer {
    pub transfer_id: Uuid,
    pub mesh_id: MeshId,
    pub model_id: ModelId,
    pub target_node: NodeId,
    pub sources: Vec<NodeId>,
    pub total_size_bytes: u64,
    pub max_bandwidth_percent: u8,
    pub status: TransferStatus,
    pub started_at: DateTime<Utc>,
    pub completed_at: Option<DateTime<Utc>>,
    pub chunks: Vec<ChunkAssignment>,
    pub bytes_transferred: u64,
    pub expected_checksum: String,
}

/// Peer info for transfer source selection.
#[derive(Debug, Clone)]
pub struct TransferPeer {
    pub node_id: NodeId,
    pub has_model: bool,
    pub is_online: bool,
    pub estimated_bandwidth_mbps: f64,
    pub current_load_percent: f64,
}

/// Accounting record generated by a transfer.
#[derive(Debug, Clone)]
pub struct TransferAccountingEntry {
    pub source_node: NodeId,
    pub target_node: NodeId,
    pub bytes_transferred: u64,
    pub record_type: AccountingType,
}

// ─── Transfer Coordinator ────────────────────────────────────────────────────

/// Coordinates model transfers between mesh peers.
pub struct MeshTransferCoordinator {
    /// Active transfers.
    active_transfers: HashMap<Uuid, ModelTransfer>,
    /// Completed transfers (for history).
    completed_transfers: Vec<ModelTransfer>,
    /// Default max bandwidth percent (default: 30).
    pub max_bandwidth_percent: u8,
    /// Chunk size for parallel transfers (default: 64MB).
    pub chunk_size_bytes: u64,
    /// Threshold for parallel transfer (default: 2GB).
    pub parallel_threshold_bytes: u64,
    /// Max concurrent transfers (default: 10).
    pub max_concurrent_transfers: u32,
}

impl MeshTransferCoordinator {
    pub fn new() -> Self {
        Self {
            active_transfers: HashMap::new(),
            completed_transfers: Vec::new(),
            max_bandwidth_percent: 30,
            chunk_size_bytes: 64 * 1024 * 1024, // 64MB
            parallel_threshold_bytes: 2 * 1024 * 1024 * 1024, // 2GB
            max_concurrent_transfers: 10,
        }
    }

    /// Discover peers that have the target model downloaded.
    pub fn discover_transfer_sources(
        &self,
        peers: &[TransferPeer],
        _model_id: &ModelId,
    ) -> Vec<NodeId> {
        let mut sources: Vec<&TransferPeer> = peers
            .iter()
            .filter(|p| p.has_model && p.is_online)
            .collect();

        // Sort by: bandwidth (desc), load (asc)
        sources.sort_by(|a, b| {
            let score_a = a.estimated_bandwidth_mbps * (1.0 - a.current_load_percent / 100.0);
            let score_b = b.estimated_bandwidth_mbps * (1.0 - b.current_load_percent / 100.0);
            score_b
                .partial_cmp(&score_a)
                .unwrap_or(std::cmp::Ordering::Equal)
        });

        sources.iter().map(|p| p.node_id).collect()
    }

    /// Initiate a model transfer.
    pub fn initiate_transfer(
        &mut self,
        mesh_id: MeshId,
        model_id: ModelId,
        target_node: NodeId,
        sources: Vec<NodeId>,
        total_size_bytes: u64,
        expected_checksum: String,
    ) -> Result<Uuid, TransferError> {
        // Check concurrent transfer limit
        if self.active_transfers.len() >= self.max_concurrent_transfers as usize {
            return Err(TransferError::TooManyConcurrent);
        }

        if sources.is_empty() {
            return Err(TransferError::NoSourcesAvailable);
        }

        // Determine transfer strategy
        let chunks = if total_size_bytes > self.parallel_threshold_bytes && sources.len() > 1 {
            // Parallel chunk transfer
            self.create_chunk_assignments(&sources, total_size_bytes)
        } else {
            // Single-source transfer
            vec![ChunkAssignment {
                source_node: sources[0],
                offset: 0,
                size: total_size_bytes,
                received: false,
                checksum: None,
            }]
        };

        let transfer = ModelTransfer {
            transfer_id: Uuid::new_v4(),
            mesh_id,
            model_id,
            target_node,
            sources,
            total_size_bytes,
            max_bandwidth_percent: self.max_bandwidth_percent,
            status: TransferStatus::Pending,
            started_at: Utc::now(),
            completed_at: None,
            chunks,
            bytes_transferred: 0,
            expected_checksum,
        };

        let id = transfer.transfer_id;
        self.active_transfers.insert(id, transfer);
        Ok(id)
    }

    /// Create chunk assignments for parallel transfer (round-robin weighted by source count).
    fn create_chunk_assignments(
        &self,
        sources: &[NodeId],
        total_size: u64,
    ) -> Vec<ChunkAssignment> {
        let num_chunks = (total_size + self.chunk_size_bytes - 1) / self.chunk_size_bytes;
        let mut assignments = Vec::new();

        for i in 0..num_chunks {
            let source_idx = (i as usize) % sources.len();
            let offset = i * self.chunk_size_bytes;
            let size = if offset + self.chunk_size_bytes > total_size {
                total_size - offset
            } else {
                self.chunk_size_bytes
            };

            assignments.push(ChunkAssignment {
                source_node: sources[source_idx],
                offset,
                size,
                received: false,
                checksum: None,
            });
        }

        assignments
    }

    /// Record that a chunk has been received.
    pub fn record_chunk_received(
        &mut self,
        transfer_id: &Uuid,
        offset: u64,
        checksum: u32,
    ) -> Result<(), TransferError> {
        let transfer = self
            .active_transfers
            .get_mut(transfer_id)
            .ok_or(TransferError::TransferNotFound)?;

        if let Some(chunk) = transfer.chunks.iter_mut().find(|c| c.offset == offset) {
            chunk.received = true;
            chunk.checksum = Some(checksum);
            transfer.bytes_transferred += chunk.size;

            // Update progress
            let progress = transfer.bytes_transferred as f64 / transfer.total_size_bytes as f64;
            transfer.status = TransferStatus::InProgress {
                progress_percent: progress * 100.0,
            };
        }

        Ok(())
    }

    /// Verify the completed transfer using SHA-256.
    pub fn verify_transfer(
        &mut self,
        transfer_id: &Uuid,
        actual_checksum: &str,
    ) -> Result<bool, TransferError> {
        let transfer = self
            .active_transfers
            .get_mut(transfer_id)
            .ok_or(TransferError::TransferNotFound)?;

        let verified = actual_checksum == transfer.expected_checksum;

        if verified {
            transfer.status = TransferStatus::Completed {
                checksum_verified: true,
            };
            transfer.completed_at = Some(Utc::now());
        } else {
            transfer.status = TransferStatus::Failed {
                reason: "SHA-256 checksum mismatch".to_string(),
            };
        }

        Ok(verified)
    }

    /// Complete a transfer and generate accounting entries.
    pub fn complete_transfer(
        &mut self,
        transfer_id: &Uuid,
    ) -> Result<Vec<TransferAccountingEntry>, TransferError> {
        let transfer = self
            .active_transfers
            .remove(transfer_id)
            .ok_or(TransferError::TransferNotFound)?;

        // Generate accounting entries for each source
        let mut entries = Vec::new();
        let mut source_bytes: HashMap<NodeId, u64> = HashMap::new();

        for chunk in &transfer.chunks {
            if chunk.received {
                *source_bytes.entry(chunk.source_node).or_insert(0) += chunk.size;
            }
        }

        for (source, bytes) in source_bytes {
            entries.push(TransferAccountingEntry {
                source_node: source,
                target_node: transfer.target_node,
                bytes_transferred: bytes,
                record_type: AccountingType::ModelTransfer,
            });
        }

        self.completed_transfers.push(transfer);
        Ok(entries)
    }

    /// Get the status of a transfer.
    pub fn get_status(&self, transfer_id: &Uuid) -> Option<&TransferStatus> {
        self.active_transfers.get(transfer_id).map(|t| &t.status)
    }

    /// Get the bandwidth limit for a transfer as bytes per second.
    pub fn bandwidth_limit_bps(&self, link_bandwidth_mbps: f64) -> u64 {
        let limit_mbps = link_bandwidth_mbps * (self.max_bandwidth_percent as f64 / 100.0);
        (limit_mbps * 1_000_000.0 / 8.0) as u64 // Convert Mbps to bytes/sec
    }

    /// Get active transfer count.
    pub fn active_count(&self) -> usize {
        self.active_transfers.len()
    }
}

/// Compute SHA-256 checksum of data.
pub fn compute_sha256(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    let result = hasher.finalize();
    result.iter().map(|b| format!("{:02x}", b)).collect()
}

/// Errors during transfer operations.
#[derive(Debug, Clone, PartialEq)]
pub enum TransferError {
    TooManyConcurrent,
    NoSourcesAvailable,
    TransferNotFound,
    ChecksumMismatch,
}

impl std::fmt::Display for TransferError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::TooManyConcurrent => write!(f, "Too many concurrent transfers"),
            Self::NoSourcesAvailable => write!(f, "No transfer sources available"),
            Self::TransferNotFound => write!(f, "Transfer not found"),
            Self::ChecksumMismatch => write!(f, "Checksum mismatch after transfer"),
        }
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    proptest! {
        /// Property: transfer bandwidth never exceeds 30% of link.
        #[test]
        fn prop_bandwidth_never_exceeds_30_percent(
            link_mbps in 10.0f64..10000.0
        ) {
            let coordinator = MeshTransferCoordinator::new();
            let limit = coordinator.bandwidth_limit_bps(link_mbps);
            let link_bps = (link_mbps * 1_000_000.0 / 8.0) as u64;

            let ratio = limit as f64 / link_bps as f64;
            prop_assert!(
                ratio <= 0.301, // Small tolerance for floating point
                "Bandwidth ratio {:.4} exceeds 30%", ratio
            );
        }

        /// Property: integrity check catches corruption (different checksums never match).
        #[test]
        fn prop_integrity_catches_corruption(
            data_a in proptest::collection::vec(any::<u8>(), 10..100),
            data_b in proptest::collection::vec(any::<u8>(), 10..100)
        ) {
            let hash_a = compute_sha256(&data_a);
            let hash_b = compute_sha256(&data_b);

            if data_a != data_b {
                prop_assert_ne!(hash_a, hash_b, "Different data should produce different checksums");
            }
        }

        /// Property: accounting records created for both parties.
        #[test]
        fn prop_accounting_for_both_parties(
            num_sources in 1usize..4,
            size_mb in 100u64..5000
        ) {
            let mut coordinator = MeshTransferCoordinator::new();
            let mesh_id = Uuid::new_v4();
            let target = Uuid::new_v4();
            let sources: Vec<NodeId> = (0..num_sources).map(|_| Uuid::new_v4()).collect();
            let total_bytes = size_mb * 1024 * 1024;

            let transfer_id = coordinator.initiate_transfer(
                mesh_id,
                "test-model".to_string(),
                target,
                sources.clone(),
                total_bytes,
                "abc123".to_string(),
            ).unwrap();

            // Mark all chunks as received
            let transfer = coordinator.active_transfers.get(&transfer_id).unwrap();
            let offsets: Vec<u64> = transfer.chunks.iter().map(|c| c.offset).collect();
            for offset in offsets {
                coordinator.record_chunk_received(&transfer_id, offset, 0).unwrap();
            }

            // Complete and get accounting
            let entries = coordinator.complete_transfer(&transfer_id).unwrap();

            // Every source that contributed should have an accounting entry
            prop_assert!(!entries.is_empty(), "Should have accounting entries");

            // All entries should reference the target node
            for entry in &entries {
                prop_assert_eq!(entry.target_node, target);
                prop_assert!(sources.contains(&entry.source_node));
            }

            // Total bytes across all entries should equal total transfer size
            let total_accounted: u64 = entries.iter().map(|e| e.bytes_transferred).sum();
            prop_assert_eq!(total_accounted, total_bytes);
        }
    }

    // ─── Unit Tests ──────────────────────────────────────────────────────────

    #[test]
    fn test_single_source_transfer() {
        let mut coordinator = MeshTransferCoordinator::new();
        let source = Uuid::new_v4();
        let target = Uuid::new_v4();

        let id = coordinator
            .initiate_transfer(
                Uuid::new_v4(),
                "small-model".to_string(),
                target,
                vec![source],
                1_000_000_000, // 1GB — below parallel threshold
                "checksum123".to_string(),
            )
            .unwrap();

        let transfer = coordinator.active_transfers.get(&id).unwrap();
        assert_eq!(transfer.chunks.len(), 1); // Single chunk
        assert_eq!(transfer.chunks[0].source_node, source);
    }

    #[test]
    fn test_parallel_transfer_multiple_sources() {
        let mut coordinator = MeshTransferCoordinator::new();
        let sources = vec![Uuid::new_v4(), Uuid::new_v4(), Uuid::new_v4()];
        let target = Uuid::new_v4();

        let id = coordinator
            .initiate_transfer(
                Uuid::new_v4(),
                "large-model".to_string(),
                target,
                sources.clone(),
                3_000_000_000, // 3GB — above parallel threshold
                "checksum456".to_string(),
            )
            .unwrap();

        let transfer = coordinator.active_transfers.get(&id).unwrap();
        assert!(transfer.chunks.len() > 1);

        // Chunks should be distributed across sources
        let source_set: std::collections::HashSet<NodeId> =
            transfer.chunks.iter().map(|c| c.source_node).collect();
        assert!(source_set.len() > 1);
    }

    #[test]
    fn test_verify_correct_checksum() {
        let mut coordinator = MeshTransferCoordinator::new();
        let data = b"test model data";
        let checksum = compute_sha256(data);

        let id = coordinator
            .initiate_transfer(
                Uuid::new_v4(),
                "model".to_string(),
                Uuid::new_v4(),
                vec![Uuid::new_v4()],
                data.len() as u64,
                checksum.clone(),
            )
            .unwrap();

        let verified = coordinator.verify_transfer(&id, &checksum).unwrap();
        assert!(verified);
    }

    #[test]
    fn test_verify_wrong_checksum_fails() {
        let mut coordinator = MeshTransferCoordinator::new();

        let id = coordinator
            .initiate_transfer(
                Uuid::new_v4(),
                "model".to_string(),
                Uuid::new_v4(),
                vec![Uuid::new_v4()],
                1000,
                "expected_hash".to_string(),
            )
            .unwrap();

        let verified = coordinator.verify_transfer(&id, "wrong_hash").unwrap();
        assert!(!verified);
    }

    #[test]
    fn test_no_sources_error() {
        let mut coordinator = MeshTransferCoordinator::new();
        let result = coordinator.initiate_transfer(
            Uuid::new_v4(),
            "model".to_string(),
            Uuid::new_v4(),
            vec![], // No sources
            1000,
            "hash".to_string(),
        );
        assert_eq!(result, Err(TransferError::NoSourcesAvailable));
    }

    #[test]
    fn test_peer_discovery_ranking() {
        let coordinator = MeshTransferCoordinator::new();
        let fast_peer = TransferPeer {
            node_id: Uuid::new_v4(),
            has_model: true,
            is_online: true,
            estimated_bandwidth_mbps: 1000.0,
            current_load_percent: 10.0,
        };
        let slow_peer = TransferPeer {
            node_id: Uuid::new_v4(),
            has_model: true,
            is_online: true,
            estimated_bandwidth_mbps: 100.0,
            current_load_percent: 50.0,
        };
        let offline_peer = TransferPeer {
            node_id: Uuid::new_v4(),
            has_model: true,
            is_online: false,
            estimated_bandwidth_mbps: 5000.0,
            current_load_percent: 0.0,
        };

        let sources = coordinator.discover_transfer_sources(
            &[slow_peer.clone(), fast_peer.clone(), offline_peer],
            &"model".to_string(),
        );

        assert_eq!(sources.len(), 2); // Offline excluded
        assert_eq!(sources[0], fast_peer.node_id); // Fast peer first
    }
}
